name: ci-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish
    - name: Upload App Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Foodworld App
        path: /home/runner/work/foodworld/foodworld/FoodWorld/bin/Debug/net5.0/publish/
